#TODO: add classifiers and readme, fix stupid packages

[project]
name = "GreenhousePython"
version = "0.0.0"
description = "It's a python thing that automates a greenhouse."
license = "MIT"
license-files = [ "LICENSE*", "LICENCE*", "COPYING*", "AUTHORS*", "NOTICE*", "LICENSES/**/*" ]
requires-python = ">=3.10"
authors = [ { name = "We need to actually go and get the names of the people who should go here." } ]
maintainers = [ { name = "We need to actually go and get the names of the people who should go here." } ]
keywords = [ "greenhouse", "automation", "the music of the spheres" ]
dependencies = [ "RPi.GPIO>=0.7.1", "picamera2>=0.3.33", "opencv-python>=4.12.0.88", "pillow>=12.0.0", "suntime>=1.3.2", "Adafruit-Blinka>=8.68.0", "adafruit-circuitpython-mcp3xxx>=1.4.22", "poetry>=2.2.1" ]

[build-system]
requres = ["poetry-core>2.0.0,<3.0,0"]
build-backend = "poetry.core.masonry.api"

[project.urls]
homepage = "https://mcpasd.k12.wi.us/"
repository = "https://github.com/sp29174/GreenhousePython"
documentation = "https://www.youtube.com/watch?v=dQw4w9WgXcQ"

[tool.poetry]
package-mode = false
packages = [ { include = "*" } ]
